site_name: PyLegifrance
site_description: Librairie Python qui simplifie l'accès aux données juridiques françaises via l'API Legifrance
site_author: PyLegifrance
site_url: https://pylegifrance.github.io/pylegifrance/
repo_url: https://github.com/pylegifrance/pylegifrance
repo_name: pylegifrance/pylegifrance
edit_uri: edit/main/docs/

theme:
  name: material
  language: fr
  logo: assets/images/logo.svg
  favicon: assets/images/logo.svg
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Passer au mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Passer au mode clair
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.blocks.tab:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search:
      lang: fr
  - tags:
  - awesome-pages
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pylegifrance/pylegifrance
      name: PyLegifrance sur GitHub
  open_graph:
    site_name: PyLegifrance
    title: PyLegifrance - Librairie Python pour l'API Legifrance
    description: Librairie Python qui simplifie l'accès aux données juridiques françaises via l'API Legifrance
    image: assets/images/social-card.png
    url: https://pylegifrance.github.io/pylegifrance/
    type: website

extra_css:
  - assets/stylesheets/extra.css
