name: Auto-merge

on:
  pull_request:
    types: [opened, reopened]

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - run: gh pr merge "$PR_URL" --auto --squash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
