name: Release to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: self-hosted
    permissions:
      contents: read
      id-token: write
    container:
      image: python:3.12

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Common Environment
        uses: ./.github/actions/setup
        with:
          install-dependencies: "true"

      - name: Build pylegifrance
        run: uv build

      - name: Check Version Consistency
        run: |
          RAW_TAG_NAME="${GITHUB_REF##*/}"
          TAG_VERSION="${RAW_TAG_NAME#v}"
          PROJECT_VERSION=$(awk -F\" '/^version =/ {print $2}' pyproject.toml)
          if [ "$TAG_VERSION" != "$PROJECT_VERSION" ]; then
            echo "Tag version ($TAG_VERSION) does not match pyproject.toml version ($PROJECT_VERSION)"
            exit 1
          fi

      - name: Publish pylegifrance to PyPI
        run: uv publish
