name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  pull_request_target:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    container:
      image: python:3.12

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.ref }}

      - name: Setup Common Environment
        uses: ./.github/actions/setup
        with:
          install-dependencies: "true"
          extras: "true"
          create-env-file: "true"
          env-content: ${{ secrets.ENV }}

      - name: Run tests
        run: uv run pytest tests
