name: Test

on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: self-hosted
    container:
      image: python:3.12

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Common Environment
        uses: ./.github/actions/setup
        with:
          extras: "true"
          env-content: ${{ secrets.ENV }}

      - name: Run tests
        run: uv run pytest tests
