name: Test

on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]
    container:
      image: python:${{ matrix.python-version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Common Environment
        uses: ./.github/actions/setup
        with:
          extras: "true"
          env-content: ${{ secrets.ENV }}

      - name: Run tests
        run: uv run pytest tests
