name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    container:
      image: python:3.12

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Common Environment
        uses: ./.github/actions/setup
        with:
          install-all-extras: "true"
          env-content: ${{ secrets.ENV }}

      - name: Run tests
        run: uv run pytest pylegifrance/test
